<?php

namespace MailPoetVendor;

// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInit44a02ee26365e83ac27f037587fedb85::getLoader();
